AppClient/Models/Address.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace AppClient.Models
{
    public class Address
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
    }
}

AppClient/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace AppClient.Models
{
    public class Book
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string ISBN { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public Address Location { get; set; }
        [Required]
        public Press Press { get; set; }
    }
}

AppClient/Models/CreateBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AppClient.Models
{
    public class CreateBook
    {
        [Required]
        public string ISBN { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public Address Location { get; set; }
        [Required]
        public Press Press { get; set; }
    }
}

AppClient/Models/ErrorViewModel.cs
namespace AppClient.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AppClient/Models/Press.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace AppClient.Models
{
    public class Press
    {
        [JsonIgnore]
        public int Id { get; set; }
        public string Name { get; set; }
        public string category { get; set; }
    }
}

AppClient/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Threading.Tasks;
using AppClient.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AppClient.Controllers
{
    public class BooksController : Controller
    {
        private readonly HttpClient client;
        private string BooksApiUrl = "";

        public BooksController()
        {
            client = new HttpClient();
            BooksApiUrl = "https://localhost:5001/Odata/Books";
            var contentType = "application/json";
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue(contentType));

        }

        public async Task<IActionResult> Index()
        {
            var response = await client.GetAsync(BooksApiUrl);
            string strData = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };
            var data = JsonSerializer.Deserialize<JsonDocument>(strData, options).RootElement;
            var booksElement = data.GetProperty("value");

            // Deserialize the "value" property into a list of Book objects.
            var books = JsonSerializer.Deserialize<IEnumerable<Book>>(booksElement.GetRawText(), options);



            return View(books);
        }

        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateBook book)
        {
            var bookJson = JsonSerializer.Serialize(book);
            var content = new StringContent(bookJson, Encoding.UTF8, "application/json");

            var response = await client.PostAsync(BooksApiUrl, content);
            if (!(response.IsSuccessStatusCode))
            {
                return NoContent();
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var response = await client.DeleteAsync(BooksApiUrl + "/" + id.ToString());
            if (!(response.IsSuccessStatusCode))
            {
                return NoContent();
            }
            return RedirectToAction("Index");


        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await client.GetAsync($"{BooksApiUrl}({id})");

            if (response.IsSuccessStatusCode)
            {
                string strData = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                };
                var book = JsonSerializer.Deserialize<Book>(strData, options);

                if (book != null)
                {
                    return View(book); // Display the edit view with the book data
                }
            }

            return RedirectToAction("Index"); // Redirect to the index page if the book is not found or if there's an error
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Book book)
        {
            if (id != book.Id)
            {
                return BadRequest();
            }

            var bookJson = JsonSerializer.Serialize(book);
            var content = new StringContent(bookJson, Encoding.UTF8, "application/json");

            var response = await client.PutAsync($"{BooksApiUrl}({id})", content);

            if (response.IsSuccessStatusCode)
            {
                // Handle success, e.g., show a success message and redirect to the index page
                TempData["Message"] = "Book updated successfully";
                return RedirectToAction("Index");
            }
            else
            {
                // Handle the case where the update failed, e.g., display an error message
                TempData["Error"] = "An error occurred while updating the book";
                return View(book); // Return the edit view with the book data to allow the user to correct errors
            }
        }
        public async Task<IActionResult> Details(int id)
        {
            var response = await client.GetAsync($"{BooksApiUrl}({id})");

            if (response.IsSuccessStatusCode)
            {
                string strData = await response.Content.ReadAsStringAsync();
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                };
                var book = JsonSerializer.Deserialize<Book>(strData, options);

                if (book != null)
                {
                    return View(book); // Display the details view with the book details
                }
            }

            return RedirectToAction("Index"); // Redirect to the index page if the book is not found or if there's an error
        }


    }
}

AppClient/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AppClient.Models;

namespace AppClient.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AppClient/Views/Books/Create.cshtml
@using AppClient.Models
@model Book

@{
    ViewData["Title"] = "Create";
}
<h1>Create</h1>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" required/>
    </div>
    <div class="form-group">
        <label asp-for="Author" class="control-label"></label>
        <input asp-for="Author" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="ISBN" class="control-label"></label>
        <input asp-for="ISBN" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Price" class="control-label"></label>
        <input asp-for="Price" class="form-control" required />
    </div>
    <div class="form-group">
        <label class="control-label">PressName</label>
        <input asp-for="Press.Name" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Press.category" class="control-label"></label>
        <input asp-for="Press.category" class="form-control" required />
    </div>
    <div class="form-group">
        <b style="color:red">Category must is: [Book, 1, 2]</b>
    </div>
    <div class="form-group">
        <label asp-for="Location.City" class="control-label"></label>
        <input asp-for="Location.City" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Location.Street" class="control-label"></label>
        <input asp-for="Location.Street" class="form-control" required />
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

AppClient/Views/Books/Details.cshtml
@model AppClient.Models.Book

<h2>Book Details</h2>

<dl class="row">
    <dt class="col-sm-2">Title</dt>
    <dd class="col-sm-10">@Model.Title</dd>

    <dt class="col-sm-2">Author</dt>
    <dd class="col-sm-10">@Model.Author</dd>

    <dt class="col-sm-2">ISBN</dt>
    <dd class="col-sm-10">@Model.ISBN</dd>

    <dt class="col-sm-2">Price</dt>
    <dd class="col-sm-10">@Model.Price.ToString("C")</dd>
</dl>

<a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
<a asp-action="Index" class="btn btn-secondary">Back to List</a>

AppClient/Views/Books/Edit.cshtml
@model AppClient.Models.Book

<h2>Edit Book</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="ISBN"></label>
        <input asp-for="ISBN" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-secondary">Cancel</a>
</form>

AppClient/Views/Books/Index.cshtml
@using AppClient.Models
@model IEnumerable<Book>

@{
    ViewData["Title"] = "Home Page";
}
<h1>Books</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<table class="table" id="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>



            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                  <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ISBN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | <a asp-action="Details"
                        asp-route-id="@item.Id">Details</a> | <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>

        }
    </tbody>
</table>

AppClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppClient.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0-alpha3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Book Manage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
     <script defer src="https://code.jquery.com/jquery-3.5.1.js"></script>
   <script defer src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script defer src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
</body>
</html>